# Site settings
title: Shida Tao
email: taoshida20@mails.ucas.ac.cn
description: >
  Master student at VIPL, Institute of Computing Technology, Chinese Academy of Sciences.
  Research interest: Embodied AI, Robot Navigation.

author:
  name: Shida Tao
  affiliation: VIPL, Institute of Computing Technology, Chinese Academy of Sciences

# Build settings
markdown: kramdown
theme: academicpages
plugins:
  - jekyll-seo-tag